/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotizarRouteImport } from './routes/cotizar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as TratamientoDeDatosRouteImport } from './routes/tratamiento-de-datos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizarRoute = CotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientoDeDatosRoute = TratamientoDeDatosRouteImport.update({
  id: '/tratamiento-de-datos',
  path: '/tratamiento-de-datos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotizar': typeof CotizarRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tratamiento-de-datos': typeof TratamientoDeDatosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotizar': typeof CotizarRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tratamiento-de-datos': typeof TratamientoDeDatosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotizar': typeof CotizarRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tratamiento-de-datos': typeof TratamientoDeDatosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cotizar'
    | '/privacidad'
    | '/terminos-y-condiciones'
    | '/tratamiento-de-datos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cotizar'
    | '/privacidad'
    | '/terminos-y-condiciones'
    | '/tratamiento-de-datos'
  id:
    | '__root__'
    | '/'
    | '/cotizar'
    | '/privacidad'
    | '/terminos-y-condiciones'
    | '/tratamiento-de-datos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotizarRoute: typeof CotizarRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  TratamientoDeDatosRoute: typeof TratamientoDeDatosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizar': {
      id: '/cotizar'
      path: '/cotizar'
      fullPath: '/cotizar'
      preLoaderRoute: typeof CotizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamiento-de-datos': {
      id: '/tratamiento-de-datos'
      path: '/tratamiento-de-datos'
      fullPath: '/tratamiento-de-datos'
      preLoaderRoute: typeof TratamientoDeDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotizarRoute: CotizarRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  TratamientoDeDatosRoute: TratamientoDeDatosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
